let coffeProducts=[
  {
    id: 1,
    title: "Breve",
    image: "coffee6.jpg",
    price: 16.3,
    category: "Latte",
  },
  {
    id: 2,
    title: "Irish Coffee",
    image: "coffee1.jpg",
    price: 11.0,
    category: "Cappuccino",
  },
  {
    id: 3,
    title: "Doppio",
    image: "coffee9.jpg",
    price: 11.6,
    category: "Americano",
  },
  {
    id: 4,
    title: "Breve",
    image: "coffee13.jpg",
    price: 11.9,
    category: "Irish Coffee",
  },
  {
    id: 5,
    title: "Americano",
    image: "coffee14.jpg",
    price: 18.4,
    category: "Macchiato",
  },
  {
    id: 6,
    title: "Turkish Coffee",
    image: "coffee7.jpg",
    price: 11.3,
    category: "Flat White",
  },
  {
    id: 7,
    title: "Turkish Coffee",
    image: "coffee18.jpg",
    price: 5.5,
    category: "Cappuccino",
  },
  {
    id: 8,
    title: "Black Eye",
    image: "coffee6.jpg",
    price: 16.8,
    category: "Mocha",
  },
  {
    id: 9,
    title: "Affogato",
    image: "coffee5.jpg",
    price: 8.4,
    category: "Latte",
  },
  {
    id: 10,
    title: "Doppio",
    image: "coffee20.jpg",
    price: 13.6,
    category: "Macchiato",
  },
  {
    id: 11,
    title: "Flat White",
    image: "coffee3.jpg",
    price: 7.8,
    category: "Americano",
  },
  {
    id: 12,
    title: "Flat White",
    image: "coffee20.jpg",
    price: 5.9,
    category: "Cappuccino",
  },
  {
    id: 13,
    title: "Doppio",
    image: "coffee16.jpg",
    price: 11.2,
    category: "Mocha",
  },
  {
    id: 14,
    title: "Latte",
    image: "coffee3.jpg",
    price: 11.4,
    category: "Macchiato",
  },
  {
    id: 15,
    title: "Macchiato",
    image: "coffee18.jpg",
    price: 14.2,
    category: "Mocha",
  },
  {
    id: 16,
    title: "Ristretto",
    image: "coffee1.jpg",
    price: 15.3,
    category: "Macchiato",
  },
  {
    id: 17,
    title: "Americano",
    image: "coffee19.jpg",
    price: 5.8,
    category: "Irish Coffee",
  },
  {
    id: 18,
    title: "Turkish Coffee",
    image: "coffee14.jpg",
    price: 12.5,
    category: "Irish Coffee",
  },
  {
    id: 19,
    title: "Macchiato",
    image: "coffee9.jpg",
    price: 9.8,
    category: "Latte",
  },
  {
    id: 20,
    title: "Black Eye",
    image: "coffee15.jpg",
    price: 8.6,
    category: "Flat White",
  },
  {
    id: 21,
    title: "Pumpkin Spice Latte",
    image: "coffee12.jpg",
    price: 18.5,
    category: "Mocha",
  },
  {
    id: 22,
    title: "Black Eye",
    image: "coffee4.jpg",
    price: 5.0,
    category: "Espresso",
  },
  {
    id: 23,
    title: "Viennese Coffee",
    image: "coffee6.jpg",
    price: 16.6,
    category: "Mocha",
  },
  {
    id: 24,
    title: "Dirty Chai",
    image: "coffee7.jpg",
    price: 10.6,
    category: "Americano",
  },
  {
    id: 25,
    title: "Espresso",
    image: "coffee17.jpg",
    price: 10.9,
    category: "Irish Coffee",
  },
  {
    id: 26,
    title: "Black Eye",
    image: "coffee6.jpg",
    price: 9.7,
    category: "Mocha",
  },
  {
    id: 27,
    title: "Viennese Coffee",
    image: "coffee6.jpg",
    price: 20.9,
    category: "Irish Coffee",
  },
  {
    id: 28,
    title: "Latte",
    image: "coffee3.jpg",
    price: 2.1,
    category: "Cappuccino",
  },
  {
    id: 29,
    title: "Viennese Coffee",
    image: "coffee9.jpg",
    price: 14.7,
    category: "Irish Coffee",
  },
  {
    id: 30,
    title: "Bulletproof Coffee",
    image: "coffee19.jpg",
    price: 11.3,
    category: "Macchiato",
  },
  {
    id: 31,
    title: "Cappuccino",
    image: "coffee18.jpg",
    price: 18.7,
    category: "Mocha",
  },
  {
    id: 32,
    title: "Affogato",
    image: "coffee14.jpg",
    price: 5.5,
    category: "Macchiato",
  },
  {
    id: 33,
    title: "Cappuccino",
    image: "coffee17.jpg",
    price: 13.1,
    category: "Macchiato",
  },
  {
    id: 34,
    title: "Americano",
    image: "coffee11.jpg",
    price: 11.2,
    category: "Irish Coffee",
  },
  {
    id: 35,
    title: "Turkish Coffee",
    image: "coffee9.jpg",
    price: 18.5,
    category: "Macchiato",
  },
  {
    id: 36,
    title: "Espresso",
    image: "coffee18.jpg",
    price: 13.3,
    category: "Espresso",
  },
  {
    id: 37,
    title: "Latte",
    image: "coffee12.jpg",
    price: 9.4,
    category: "Flat White",
  },
  {
    id: 38,
    title: "Espresso",
    image: "coffee8.jpg",
    price: 19.6,
    category: "Espresso",
  },
  {
    id: 39,
    title: "Ristretto",
    image: "coffee10.jpg",
    price: 16.7,
    category: "Americano",
  },
  {
    id: 40,
    title: "Cortado",
    image: "coffee2.jpg",
    price: 3.0,
    category: "Cappuccino",
  },
  {
    id: 41,
    title: "Americano",
    image: "coffee19.jpg",
    price: 19.7,
    category: "Americano",
  },
  {
    id: 42,
    title: "Doppio",
    image: "coffee19.jpg",
    price: 15.7,
    category: "Flat White",
  },
  {
    id: 43,
    title: "Flat White",
    image: "coffee17.jpg",
    price: 18.6,
    category: "Mocha",
  },
  {
    id: 44,
    title: "Cappuccino",
    image: "coffee8.jpg",
    price: 2.1,
    category: "Mocha",
  },
  {
    id: 45,
    title: "Flat White",
    image: "coffee4.jpg",
    price: 12.1,
    category: "Flat White",
  },
  {
    id: 46,
    title: "Irish Coffee",
    image: "coffee10.jpg",
    price: 13.9,
    category: "Cappuccino",
  },
  {
    id: 47,
    title: "Americano",
    image: "coffee8.jpg",
    price: 13.4,
    category: "Flat White",
  },
  {
    id: 48,
    title: "Macchiato",
    image: "coffee8.jpg",
    price: 10.5,
    category: "Irish Coffee",
  },
  {
    id: 49,
    title: "Doppio",
    image: "coffee2.jpg",
    price: 21.6,
    category: "Mocha",
  },
  {
    id: 50,
    title: "Black Eye",
    image: "coffee8.jpg",
    price: 12.0,
    category: "Mocha",
  },
  {
    id: 51,
    title: "Red Eye",
    image: "coffee14.jpg",
    price: 3.1,
    category: "Americano",
  },
  {
    id: 52,
    title: "Affogato",
    image: "coffee8.jpg",
    price: 14.1,
    category: "Latte",
  },
  {
    id: 53,
    title: "Affogato",
    image: "coffee15.jpg",
    price: 11.5,
    category: "Flat White",
  },
  {
    id: 54,
    title: "Macchiato",
    image: "coffee19.jpg",
    price: 19.8,
    category: "Espresso",
  },
  {
    id: 55,
    title: "Doppio",
    image: "coffee10.jpg",
    price: 7.6,
    category: "Flat White",
  },
  {
    id: 56,
    title: "Turkish Coffee",
    image: "coffee10.jpg",
    price: 17.5,
    category: "Macchiato",
  },
  {
    id: 57,
    title: "Macchiato",
    image: "coffee15.jpg",
    price: 4.6,
    category: "Latte",
  },
  {
    id: 58,
    title: "Turkish Coffee",
    image: "coffee14.jpg",
    price: 11.2,
    category: "Latte",
  },
  {
    id: 59,
    title: "Red Eye",
    image: "coffee5.jpg",
    price: 3.4,
    category: "Mocha",
  },
  {
    id: 60,
    title: "Viennese Coffee",
    image: "coffee13.jpg",
    price: 13.6,
    category: "Mocha",
  },
  {
    id: 61,
    title: "Flat White",
    image: "coffee6.jpg",
    price: 12.1,
    category: "Mocha",
  },
  {
    id: 62,
    title: "Flat White",
    image: "coffee13.jpg",
    price: 8.9,
    category: "Macchiato",
  },
  {
    id: 63,
    title: "Affogato",
    image: "coffee5.jpg",
    price: 18.4,
    category: "Cappuccino",
  },
  {
    id: 64,
    title: "Macchiato",
    image: "coffee10.jpg",
    price: 17.0,
    category: "Mocha",
  },
  {
    id: 65,
    title: "Pumpkin Spice Latte",
    image: "coffee1.jpg",
    price: 10.7,
    category: "Cappuccino",
  },
  {
    id: 66,
    title: "Black Eye",
    image: "coffee5.jpg",
    price: 21.3,
    category: "Irish Coffee",
  },
  {
    id: 67,
    title: "Macchiato",
    image: "coffee16.jpg",
    price: 18.5,
    category: "Espresso",
  },
  {
    id: 68,
    title: "Ristretto",
    image: "coffee11.jpg",
    price: 19.3,
    category: "Mocha",
  },
  {
    id: 69,
    title: "Latte",
    image: "coffee8.jpg",
    price: 5.6,
    category: "Macchiato",
  },
  {
    id: 70,
    title: "Ristretto",
    image: "coffee20.jpg",
    price: 14.4,
    category: "Irish Coffee",
  },
  {
    id: 71,
    title: "Affogato",
    image: "coffee12.jpg",
    price: 14.1,
    category: "Macchiato",
  },
  {
    id: 72,
    title: "Espresso",
    image: "coffee10.jpg",
    price: 9.5,
    category: "Espresso",
  },
  {
    id: 73,
    title: "Turkish Coffee",
    image: "coffee19.jpg",
    price: 4.6,
    category: "Mocha",
  },
  {
    id: 74,
    title: "Irish Coffee",
    image: "coffee2.jpg",
    price: 11.6,
    category: "Americano",
  },
  {
    id: 75,
    title: "Flat White",
    image: "coffee9.jpg",
    price: 14.6,
    category: "Macchiato",
  },
  {
    id: 76,
    title: "Pumpkin Spice Latte",
    image: "coffee5.jpg",
    price: 12.2,
    category: "Mocha",
  },
  {
    id: 77,
    title: "Irish Coffee",
    image: "coffee20.jpg",
    price: 19.2,
    category: "Cappuccino",
  },
  {
    id: 78,
    title: "Macchiato",
    image: "coffee18.jpg",
    price: 4.1,
    category: "Cappuccino",
  },
  {
    id: 79,
    title: "Black Eye",
    image: "coffee13.jpg",
    price: 15.3,
    category: "Espresso",
  },
  {
    id: 80,
    title: "Espresso",
    image: "coffee20.jpg",
    price: 2.1,
    category: "Cappuccino",
  },
  {
    id: 81,
    title: "Black Eye",
    image: "coffee4.jpg",
    price: 7.8,
    category: "Flat White",
  },
  {
    id: 82,
    title: "Viennese Coffee",
    image: "coffee18.jpg",
    price: 21.9,
    category: "Flat White",
  },
  {
    id: 83,
    title: "Red Eye",
    image: "coffee4.jpg",
    price: 20.6,
    category: "Flat White",
  },
  {
    id: 84,
    title: "Viennese Coffee",
    image: "coffee1.jpg",
    price: 10.7,
    category: "Flat White",
  },
  {
    id: 85,
    title: "Turkish Coffee",
    image: "coffee12.jpg",
    price: 11.6,
    category: "Macchiato",
  },
  {
    id: 86,
    title: "Ristretto",
    image: "coffee16.jpg",
    price: 13.7,
    category: "Latte",
  },
  {
    id: 87,
    title: "Breve",
    image: "coffee10.jpg",
    price: 3.7,
    category: "Americano",
  },
  {
    id: 88,
    title: "Affogato",
    image: "coffee5.jpg",
    price: 2.3,
    category: "Americano",
  },
  {
    id: 89,
    title: "Irish Coffee",
    image: "coffee11.jpg",
    price: 19.3,
    category: "Macchiato",
  },
  {
    id: 90,
    title: "Red Eye",
    image: "coffee15.jpg",
    price: 19.7,
    category: "Cappuccino",
  },
  {
    id: 91,
    title: "Ristretto",
    image: "coffee20.jpg",
    price: 20.5,
    category: "Americano",
  },
  {
    id: 92,
    title: "Irish Coffee",
    image: "coffee18.jpg",
    price: 13.5,
    category: "Mocha",
  },
  {
    id: 93,
    title: "Cappuccino",
    image: "coffee16.jpg",
    price: 7.3,
    category: "Latte",
  },
  {
    id: 94,
    title: "Pumpkin Spice Latte",
    image: "coffee1.jpg",
    price: 6.9,
    category: "Latte",
  },
  {
    id: 95,
    title: "Cappuccino",
    image: "coffee3.jpg",
    price: 6.9,
    category: "Americano",
  },
  {
    id: 96,
    title: "Doppio",
    image: "coffee13.jpg",
    price: 2.7,
    category: "Flat White",
  },
  {
    id: 97,
    title: "Turkish Coffee",
    image: "coffee13.jpg",
    price: 6.9,
    category: "Macchiato",
  },
  {
    id: 98,
    title: "Mocha",
    image: "coffee13.jpg",
    price: 6.3,
    category: "Cappuccino",
  },
  {
    id: 99,
    title: "Turkish Coffee",
    image: "coffee6.jpg",
    price: 9.0,
    category: "Macchiato",
  },
  {
    id: 100,
    title: "Macchiato",
    image: "coffee8.jpg",
    price: 13.2,
    category: "Latte",
  },
  {
    id: 101,
    title: "Espresso",
    image: "coffee14.jpg",
    price: 5.2,
    category: "Americano",
  },
  {
    id: 102,
    title: "Cappuccino",
    image: "coffee19.jpg",
    price: 10.4,
    category: "Irish Coffee",
  },
  {
    id: 103,
    title: "Turkish Coffee",
    image: "coffee16.jpg",
    price: 12.1,
    category: "Americano",
  },
  {
    id: 104,
    title: "Turkish Coffee",
    image: "coffee8.jpg",
    price: 10.3,
    category: "Latte",
  },
  {
    id: 105,
    title: "Mocha",
    image: "coffee14.jpg",
    price: 19.7,
    category: "Mocha",
  },
  {
    id: 106,
    title: "Pumpkin Spice Latte",
    image: "coffee11.jpg",
    price: 14.2,
    category: "Flat White",
  },
  {
    id: 107,
    title: "Ristretto",
    image: "coffee17.jpg",
    price: 10.1,
    category: "Americano",
  },
  {
    id: 108,
    title: "Ristretto",
    image: "coffee7.jpg",
    price: 17.7,
    category: "Macchiato",
  },
  {
    id: 109,
    title: "Latte",
    image: "coffee7.jpg",
    price: 10.8,
    category: "Americano",
  },
  {
    id: 110,
    title: "Turkish Coffee",
    image: "coffee9.jpg",
    price: 5.5,
    category: "Flat White",
  },
  {
    id: 111,
    title: "Turkish Coffee",
    image: "coffee2.jpg",
    price: 21.9,
    category: "Espresso",
  },
  {
    id: 112,
    title: "Doppio",
    image: "coffee20.jpg",
    price: 6.5,
    category: "Flat White",
  },
  {
    id: 113,
    title: "Dirty Chai",
    image: "coffee9.jpg",
    price: 8.9,
    category: "Flat White",
  },
  {
    id: 114,
    title: "Flat White",
    image: "coffee3.jpg",
    price: 20.2,
    category: "Mocha",
  },
  {
    id: 115,
    title: "Irish Coffee",
    image: "coffee12.jpg",
    price: 8.7,
    category: "Mocha",
  },
  {
    id: 116,
    title: "Mocha",
    image: "coffee13.jpg",
    price: 16.3,
    category: "Mocha",
  },
  {
    id: 117,
    title: "Flat White",
    image: "coffee16.jpg",
    price: 15.2,
    category: "Mocha",
  },
  {
    id: 118,
    title: "Americano",
    image: "coffee8.jpg",
    price: 19.9,
    category: "Flat White",
  },
  {
    id: 119,
    title: "Americano",
    image: "coffee19.jpg",
    price: 15.2,
    category: "Macchiato",
  },
  {
    id: 120,
    title: "Cortado",
    image: "coffee15.jpg",
    price: 5.1,
    category: "Flat White",
  },
  {
    id: 121,
    title: "Ristretto",
    image: "coffee8.jpg",
    price: 17.5,
    category: "Macchiato",
  },
  {
    id: 122,
    title: "Doppio",
    image: "coffee7.jpg",
    price: 11.3,
    category: "Cappuccino",
  },
  {
    id: 123,
    title: "Black Eye",
    image: "coffee15.jpg",
    price: 10.4,
    category: "Espresso",
  },
  {
    id: 124,
    title: "Mocha",
    image: "coffee15.jpg",
    price: 16.7,
    category: "Irish Coffee",
  },
  {
    id: 125,
    title: "Black Eye",
    image: "coffee2.jpg",
    price: 18.0,
    category: "Americano",
  },
];
